# Generated by Django 3.2.6 on 2024-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(blank=True, max_length=255, null=True)),
                ('dateandtime', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('auth_result', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_type', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=255, null=True)),
                ('reader_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('card_number', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stamps',
                'managed': False,
            },
        ),
    ]
